#!/usr/bin/env bash
# build-install.sh - Build and install ralph-tui
# Generated by repo-mole

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "==> Installing dependencies..."
bun install

echo "==> Building ralph-tui..."
bun run build

echo "==> Type checking..."
bun run typecheck

# Create bin directory if needed
BIN_DIR="$HOME/prj/util/bin"
mkdir -p "$BIN_DIR"

# Symlink the binary
BINARY="$SCRIPT_DIR/dist/cli.js"
LINK="$BIN_DIR/ralph-tui"

if [ -L "$LINK" ] || [ -e "$LINK" ]; then
    rm "$LINK"
fi

ln -s "$BINARY" "$LINK"

echo ""
echo "✓ ralph-tui installed successfully!"
echo "  Binary: $LINK"
echo "  Source: $SCRIPT_DIR"
echo ""
echo "Ensure ~/prj/util/bin is in your PATH:"
echo "  export PATH=\"\$HOME/prj/util/bin:\$PATH\""
